version: "3.7"

services:
  api:
    container_name: "GAME_API"
    build:
      context: .
      target: prod
    ports:
      - "80:8000"
    env_file:
      - .env.prod
    environment:
      - ENV=prod
    networks:
      - backend
    depends_on:
      - postgres
    volumes:
      - game-logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
        labels: "app=high_logging"
        env: "ENV,DEBUG"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"

  postgres:
    container_name: "postgres"
    image: postgres
    hostname: db
    ports:
      - "5432:5432"
    env_file:
      - .env.prod

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data

  healthcheck_service:
    image: fvergaracl/game-health-check:latest
    container_name: health_checker
    env_file:
      - .env.prod
    environment:
      DB_HOST: "postgres"
      API_URL_KPI: "http://api:8000/api/v1/kpi"
    depends_on:
      - postgres
    networks:
      - backend
      - api

networks:
  backend:
    driver: "bridge"

volumes:
  postgres-data:
  game-logs:
