version: "3.3"
services:
  postgres:
    container_name: "postgresGAME-DEV"
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: game_dev_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
