# Settings related with https://github.com/Greengage-project/interlink-project
version: "3.7"

services:
  api:
    container_name: "GAME_API_DEV"
    build:
      context: .
      target: dev
    ports:
      - "8000:8000"
    env_file:
      - .env.integrated
    environment:
      - ENV=dev
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=debug
    networks:
      - traefik-public
    volumes:
      - ./app:/app/app
      - ./migrations:/app/migrations
      - game-logs:/app/logs
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.GAME_API_DEV.rule=PathPrefix(`/gamengine`)
      - traefik.http.middlewares.strip-gamengine.stripprefix.prefixes=/gamengine
      - traefik.http.routers.GAME_API_DEV.middlewares=strip-gamengine
      - traefik.http.services.GAME_API_DEV.loadbalancer.server.port=8000
      
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
        labels: "app=high_logging"
        env: "ENV,DEBUG"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
  
  dashboard_game:
    container_name: "dashboard_game"
    build:
        context: ./dashboard
        dockerfile: Dockerfile
    volumes:
        - ./dashboard:/app 
        - /app/node_modules 
    environment:
        NODE_ENV: development
    depends_on:
        - api 
    labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.dashboard_game.rule=PathPrefix(`/gameDashboard`)
        - traefik.http.middlewares.strip-dashboard_game.stripprefix.prefixes=/gameDashboard
        - traefik.http.routers.dashboard_game.middlewares=strip-dashboard_game
        - traefik.http.services.dashboard_game.loadbalancer.server.port=3000
    networks:
        - traefik-public


    


  keycloakGame:
    container_name: "keycloakGame"
    image: keycloak/keycloak:25.0
    hostname: keycloak
    ports:
      - "8080:8080"
    env_file:
      - .env.integrated
    volumes:
      - keycloak-data:/opt/keycloak/data
    command: ["start-dev"]
    networks:
      - traefik-public

  healthcheck_service:
    build: ./healthcheck_service
    container_name: health_checker
    env_file:
      - .env.integrated
    environment:
      DB_HOST: "postgres"
      API_URL_KPI: "http://api:8000/api/v1/kpi"
    depends_on:
      - api
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true

volumes:
  postgres-data:
  keycloak-data:
  game-logs:
