version: "3.7"

services:
  api:
    container_name: "GAME_API"
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "80:8000"
    env_file:
      - .env.prod
    networks:
      - backend
    depends_on:
      - postgres
    volumes:
        - game-logs:/app/logs

  postgres:
    container_name: "postgres"
    image: postgres
    hostname: db
    ports:
      - "5432:5432"
    env_file:
      - .env.prod

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  backend:
    driver: "bridge"

volumes:
  postgres-data:
  game-logs:
