version: "3.7"

services:
  postgres:
    container_name: "postgres"
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  keycloak:
    container_name: "keycloak"
    image: keycloak/keycloak:25.0
    hostname: keycloak
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    command: ["start-dev"]

networks:
  backend:
    driver: "bridge"

volumes:
  postgres-data:
  keycloak-data:

