version: "3.7"

services:
  postgres:
    container_name: "db"
    image: postgres
    hostname: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: game_dev_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: "bridge"

volumes:
  postgres-data:
