"""Sphinx configuration for the GAME documentation site.

The site is built by ``.github/workflows/deploy_documentation.yml`` with::

    poetry run sphinx-build -b html docs/source _build/html

and published to the ``gh-pages`` branch on every push to ``main``.

Project metadata (version, author, license) is single-sourced from
``pyproject.toml`` so the documentation never drifts from the package it
documents. If ``pyproject.toml`` cannot be read for any reason (for
example when the docs are built from an unusual working directory) the
build degrades gracefully to the literals below instead of failing.
"""

import os
import sys
from pathlib import Path

# Make the application package importable so ``autodoc`` can introspect it.
# ``docs/source`` -> repository root is two levels up.
sys.path.insert(0, os.path.abspath("../.."))

try:  # Python >= 3.11 ships tomllib in the standard library.
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - fallback for older runners
    tomllib = None


def _read_project_metadata() -> dict:
    """Return ``[tool.poetry]`` metadata, or sane defaults on failure."""
    defaults = {
        "version": "0.0.0",
        "authors": ["fvergaracl <felipe.vergara@deusto.es>"],
        "license": "Apache-2.0",
    }
    if tomllib is None:
        return defaults
    pyproject = Path(__file__).resolve().parents[2] / "pyproject.toml"
    try:
        with pyproject.open("rb") as handle:
            data = tomllib.load(handle)
        return {**defaults, **data["tool"]["poetry"]}
    except (OSError, KeyError, ValueError):  # pragma: no cover - defensive
        return defaults


_metadata = _read_project_metadata()
_author_name = _metadata["authors"][0].split("<")[0].strip()

# -- Project information -----------------------------------------------------

project = "GAME"
copyright = f"2024-2026, {_author_name}"
author = _author_name
# ``release`` is the full version (e.g. 1.2.047); ``version`` is the short
# X.Y series shown in the header.
release = str(_metadata["version"])
version = ".".join(release.split(".")[:2])

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html

extensions = [
    "sphinx.ext.autodoc",  # pull docstrings from the app package
    "sphinx.ext.autosummary",  # generate per-module summary tables
    "sphinx.ext.intersphinx",  # cross-link to Python / Sphinx docs
    "sphinx.ext.duration",  # report slowest pages at build time
    "sphinx.ext.doctest",  # execute doctest snippets when present
    "sphinx.ext.viewcode",  # add "[source]" links next to API entries
    "sphinx.ext.napoleon",  # parse Google-style docstrings
    "sphinx.ext.todo",  # surface ``.. todo::`` directives
    "sphinxcontrib.mermaid",  # render ``.. mermaid::`` diagrams (ERD, pipelines)
]

templates_path = ["_templates"]
exclude_patterns = []

# Order autodoc members the way they appear in the source, not alphabetically;
# this keeps related methods together and matches the reading order a
# contributor would follow in the file itself.
autodoc_member_order = "bysource"
autodoc_typehints = "description"
# ``members``/``undoc-members`` are intentionally NOT forced globally.
#
# * The per-module pages generated by ``sphinx-apidoc`` carry an explicit
#   ``:members:`` already, so leaf modules are fully documented. The package
#   index pages (``app.services``, ``app.repository``, …) deliberately omit it
#   so re-exported symbols in their ``__init__`` are not documented a second
#   time under their canonical name - which would make every type reference to
#   them ambiguous ("more than one target found").
# * ``undoc-members`` is off so the Google-style ``Attributes:`` block in each
#   model docstring is the single source for columns; otherwise autodoc would
#   also enumerate the raw SQLModel fields, documenting each column twice.
autodoc_default_options = {
    "show-inheritance": True,
}
autodoc_mock_imports = []

# Napoleon (Google-style docstrings) tuning.
napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_init_with_doc = True
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_rtype = False

autosummary_generate = True

# ``.. todo::`` blocks are visible in the rendered site so unfinished
# sections are honestly flagged rather than silently empty.
todo_include_todos = True

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "sphinx": ("https://www.sphinx-doc.org/en/master/", None),
    "sqlalchemy": ("https://docs.sqlalchemy.org/en/20/", None),
    "fastapi": ("https://fastapi.tiangolo.com/", None),
}
# Never fail the build because an intersphinx inventory is unreachable.
intersphinx_disabled_reftypes = ["*"]

# -- Options for HTML output -------------------------------------------------

# The sphinx_material theme injects a callable into ``html_context``; Sphinx
# 7.4's config cache cannot pickle it and emits a (harmless) warning. Suppress
# just that category so the build stays warning-free.
suppress_warnings = ["config.cache"]

html_theme = "sphinx_material"
html_static_path = ["_static"]
html_css_files = ["custom.css"]
html_title = "GAME (Goals And Motivation Engine)"

google_analytics_account = os.getenv("GOOGLE_ANALYTICS_ACCOUNT", None)

html_theme_options = {
    "nav_title": "GAME - Goals And Motivation Engine",
    "color_primary": "blue",
    "color_accent": "light-blue",
    "repo_url": "https://github.com/fvergaracl/GAME",
    "repo_name": "fvergaracl/GAME",
    "repo_type": "github",
    "google_analytics_account": google_analytics_account,
    "globaltoc_depth": 2,
    "globaltoc_collapse": True,
    "globaltoc_includehidden": True,
    "master_doc": False,
    "version_dropdown": False,
}

html_sidebars = {
    "**": [
        "globaltoc.html",
        "localtoc.html",
        "searchbox.html",
    ]
}

# Fail the CI build on a broken internal cross-reference so dead links are
# caught in review rather than shipped. External links are checked
# separately by the ``linkcheck`` builder and are not gated here.
nitpicky = False
