"""user actions added

Revision ID: 010a18aa71e4
Revises: 7a1427d45348
Create Date: 2024-07-01 11:53:04.780608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010a18aa71e4'
down_revision = '7a1427d45348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
