"""update Task and Strategy

Revision ID: 0bbaa5703ca7
Revises: fc0435860dde
Create Date: 2024-01-19 13:26:07.324229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0bbaa5703ca7'
down_revision = 'fc0435860dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('strategyName', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategyName')
    )
    op.drop_table('strategies')
    op.add_column('tasks', sa.Column('strategyId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'strategy', ['strategyId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'strategyId')
    op.create_table('strategies',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('strategy', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('taskId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['taskId'], ['tasks.id'], name='strategies_taskId_fkey'),
    sa.PrimaryKeyConstraint('id', name='strategies_pkey'),
    sa.UniqueConstraint('strategy', name='strategies_strategy_key')
    )
    op.drop_table('strategy')
    # ### end Alembic commands ###
