"""fix strategy

Revision ID: 0bea6fc76e4e
Revises: 1a873d240a90
Create Date: 2024-01-21 16:45:22.566012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bea6fc76e4e'
down_revision = '1a873d240a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
