"""coin into Wallettransaction

Revision ID: 1640253c71d5
Revises: 3fe23d72d9fa
Create Date: 2024-01-31 11:08:59.180240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1640253c71d5'
down_revision = '3fe23d72d9fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallettransactions', sa.Column('coins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallettransactions', 'coins')
    # ### end Alembic commands ###
