"""strategyId added in game

Revision ID: 19a86cfedf6d
Revises: c0e8270b548a
Create Date: 2024-03-11 21:52:11.597913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a86cfedf6d'
down_revision = 'c0e8270b548a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('strategyId', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'strategyId')
    # ### end Alembic commands ###
