"""user's game config

Revision ID: 29addea299e4
Revises: 45127929c3be
Create Date: 2025-02-24 10:37:49.644959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29addea299e4'
down_revision = '45127929c3be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
