"""paramkey to key

Revision ID: 335e4bfcb868
Revises: ad1a314ac577
Create Date: 2024-03-11 22:33:36.416217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335e4bfcb868'
down_revision = 'ad1a314ac577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamesparams', sa.Column('key', sa.String(), nullable=True))
    op.drop_column('gamesparams', 'paramKey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamesparams', sa.Column('paramKey', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('gamesparams', 'key')
    # ### end Alembic commands ###
