"""update lowercase

Revision ID: 394e21c63ac9
Revises: c27b4e3d80ce
Create Date: 2024-01-19 10:29:45.539244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394e21c63ac9'
down_revision = 'c27b4e3d80ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('externalGameId', sa.String(), nullable=True))
    op.drop_constraint('games_externalGameID_key', 'games', type_='unique')
    op.create_unique_constraint(None, 'games', ['externalGameId'])
    op.drop_column('games', 'externalGameID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('externalGameID', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'games', type_='unique')
    op.create_unique_constraint('games_externalGameID_key', 'games', ['externalGameID'])
    op.drop_column('games', 'externalGameId')
    # ### end Alembic commands ###
