"""remove duplicated columns

Revision ID: 45127929c3be
Revises: 6330a6e2ded5
Create Date: 2024-11-18 14:36:22.200652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45127929c3be'
down_revision = '6330a6e2ded5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikey', sa.Column('oauth_user_id', sa.String(), nullable=True))
    op.drop_constraint('apikey_oauthusers_id_fkey', 'apikey', type_='foreignkey')
    op.create_foreign_key(None, 'apikey', 'oauthusers', ['oauth_user_id'], ['provider_user_id'])
    op.drop_column('apikey', 'oauthusers_id')
    op.drop_constraint('games_oauthusers_id_fkey', 'games', type_='foreignkey')
    op.drop_column('games', 'oauthusers_id')
    op.drop_constraint('gamesparams_oauthusers_id_fkey', 'gamesparams', type_='foreignkey')
    op.drop_column('gamesparams', 'oauthusers_id')
    op.drop_constraint('tasks_oauthusers_id_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'oauthusers_id')
    op.drop_constraint('tasksparams_oauthusers_id_fkey', 'tasksparams', type_='foreignkey')
    op.drop_column('tasksparams', 'oauthusers_id')
    op.drop_constraint('useractions_oauthusers_id_fkey', 'useractions', type_='foreignkey')
    op.drop_column('useractions', 'oauthusers_id')
    op.drop_constraint('userpoints_oauthusers_id_fkey', 'userpoints', type_='foreignkey')
    op.drop_column('userpoints', 'oauthusers_id')
    op.drop_constraint('users_oauthusers_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'oauthusers_id')
    op.drop_constraint('wallet_oauthusers_id_fkey', 'wallet', type_='foreignkey')
    op.drop_column('wallet', 'oauthusers_id')
    op.drop_constraint('wallettransactions_oauthusers_id_fkey', 'wallettransactions', type_='foreignkey')
    op.drop_column('wallettransactions', 'oauthusers_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallettransactions', sa.Column('oauthusers_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('wallettransactions_oauthusers_id_fkey', 'wallettransactions', 'oauthusers', ['oauthusers_id'], ['provider_user_id'])
    op.add_column('wallet', sa.Column('oauthusers_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('wallet_oauthusers_id_fkey', 'wallet', 'oauthusers', ['oauthusers_id'], ['provider_user_id'])
    op.add_column('users', sa.Column('oauthusers_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_oauthusers_id_fkey', 'users', 'oauthusers', ['oauthusers_id'], ['provider_user_id'])
    op.add_column('userpoints', sa.Column('oauthusers_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('userpoints_oauthusers_id_fkey', 'userpoints', 'oauthusers', ['oauthusers_id'], ['provider_user_id'])
    op.add_column('useractions', sa.Column('oauthusers_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('useractions_oauthusers_id_fkey', 'useractions', 'oauthusers', ['oauthusers_id'], ['provider_user_id'])
    op.add_column('tasksparams', sa.Column('oauthusers_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('tasksparams_oauthusers_id_fkey', 'tasksparams', 'oauthusers', ['oauthusers_id'], ['provider_user_id'])
    op.add_column('tasks', sa.Column('oauthusers_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('tasks_oauthusers_id_fkey', 'tasks', 'oauthusers', ['oauthusers_id'], ['provider_user_id'])
    op.add_column('gamesparams', sa.Column('oauthusers_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('gamesparams_oauthusers_id_fkey', 'gamesparams', 'oauthusers', ['oauthusers_id'], ['provider_user_id'])
    op.add_column('games', sa.Column('oauthusers_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('games_oauthusers_id_fkey', 'games', 'oauthusers', ['oauthusers_id'], ['provider_user_id'])
    op.add_column('apikey', sa.Column('oauthusers_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'apikey', type_='foreignkey')
    op.create_foreign_key('apikey_oauthusers_id_fkey', 'apikey', 'oauthusers', ['oauthusers_id'], ['provider_user_id'])
    op.drop_column('apikey', 'oauth_user_id')
    # ### end Alembic commands ###
