"""update column externalUserId

Revision ID: 4bf2a0832ad8
Revises: 28fc12067e8f
Create Date: 2024-01-22 01:44:50.346413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf2a0832ad8'
down_revision = '28fc12067e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('externalUserId', sa.String(), nullable=True))
    op.drop_constraint('users_externalUserID_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['externalUserId'])
    op.drop_column('users', 'externalUserID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('externalUserID', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_externalUserID_key', 'users', ['externalUserID'])
    op.drop_column('users', 'externalUserId')
    # ### end Alembic commands ###
