"""user actions added

Revision ID: 59843af22ade
Revises: 7a1427d45348
Create Date: 2024-07-01 13:08:40.650422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59843af22ade'
down_revision = '7a1427d45348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useractions',
                    sa.Column('id', postgresql.UUID(
                        as_uuid=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('typeAction', sa.String(), nullable=True),
                    sa.Column('data', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('userId', postgresql.UUID(
                        as_uuid=True), nullable=True),
                    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_useractions_id'),
                    'useractions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_useractions_id'), table_name='useractions')
    op.drop_table('useractions')
    # ### end Alembic commands ###
