"""fix column oauth_user_id

Revision ID: 6330a6e2ded5
Revises: f864fafa202d
Create Date: 2024-11-18 14:03:56.431922

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6330a6e2ded5"
down_revision = "f864fafa202d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("logs_oauthusers_id_fkey", "logs", type_="foreignkey")
    op.create_foreign_key(
        None, "logs", "oauthusers", ["oauth_user_id"], ["provider_user_id"]
    )
    op.drop_column("logs", "oauthusers_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "logs",
        sa.Column("oauthusers_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "logs", type_="foreignkey")
    op.create_foreign_key(
        "logs_oauthusers_id_fkey",
        "logs",
        "oauthusers",
        ["oauthusers_id"],
        ["provider_user_id"],
    )
    # ### end Alembic commands ###
