"""coins to float

Revision ID: 63dd25f00eb9
Revises: 930d9fa6bb6e
Create Date: 2024-02-01 15:04:14.290584

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "63dd25f00eb9"
down_revision = "930d9fa6bb6e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
