"""fix game model

Revision ID: 6814549b9f62
Revises: 848e459beae1
Create Date: 2024-01-16 15:53:19.043600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6814549b9f62'
down_revision = '848e459beae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
