"""fix relationship tasks - strategis

Revision ID: 6df01e4bf870
Revises: 6814549b9f62
Create Date: 2024-01-17 13:52:27.329088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df01e4bf870'
down_revision = '6814549b9f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('taskId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'strategies', 'tasks', ['taskId'], ['id'])
    op.drop_constraint('tasks_strategyId_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'strategyId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('strategyId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tasks_strategyId_fkey', 'tasks', 'strategies', ['strategyId'], ['id'])
    op.drop_constraint(None, 'strategies', type_='foreignkey')
    op.drop_column('strategies', 'taskId')
    # ### end Alembic commands ###
