"""fix game relationship with task

Revision ID: 848e459beae1
Revises: 74417719cd87
Create Date: 2024-01-16 11:51:24.148471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848e459beae1'
down_revision = '74417719cd87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('gameId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'games', ['gameId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'gameId')
    # ### end Alembic commands ###
