"""coins to float

Revision ID: 930d9fa6bb6e
Revises: f08f7721328e
Create Date: 2024-02-01 15:03:02.459501

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "930d9fa6bb6e"
down_revision = "f08f7721328e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
