"""fix relationship tasks - strategis

Revision ID: 9745cccfeb60
Revises: 6df01e4bf870
Create Date: 2024-01-17 13:53:17.959325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9745cccfeb60'
down_revision = '6df01e4bf870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
