"""taskparams model modified

Revision ID: a034877f5226
Revises: 312d9add52ce
Create Date: 2024-10-25 11:13:23.882994

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a034877f5226"
down_revision = "312d9add52ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "apirequests_apiKey_used_fkey", "apirequests", type_="foreignkey"
    )
    op.drop_constraint("kpimetrics_apiKey_used_fkey", "kpimetrics", type_="foreignkey")
    op.drop_constraint("uptimelogs_apiKey_used_fkey", "uptimelogs", type_="foreignkey")
    op.drop_constraint(
        "userinteractions_apiKey_used_fkey", "userinteractions", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "userinteractions_apiKey_used_fkey",
        "userinteractions",
        "apikey",
        ["apiKey_used"],
        ["apiKey"],
    )
    op.create_foreign_key(
        "uptimelogs_apiKey_used_fkey",
        "uptimelogs",
        "apikey",
        ["apiKey_used"],
        ["apiKey"],
    )
    op.create_foreign_key(
        "kpimetrics_apiKey_used_fkey",
        "kpimetrics",
        "apikey",
        ["apiKey_used"],
        ["apiKey"],
    )
    op.create_foreign_key(
        "apirequests_apiKey_used_fkey",
        "apirequests",
        "apikey",
        ["apiKey_used"],
        ["apiKey"],
    )
    # ### end Alembic commands ###
