"""strategyId type changed

Revision ID: acafc70e83bf
Revises: 3a9e7b35f70d
Create Date: 2024-03-12 11:35:55.273859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'acafc70e83bf'
down_revision = '3a9e7b35f70d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'strategyId',
               existing_type=postgresql.UUID(),
               type_=sa.String(),
               nullable=False)
    op.drop_constraint('tasks_strategyId_fkey', 'tasks', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('tasks_strategyId_fkey', 'tasks', 'strategy', ['strategyId'], ['id'])
    op.alter_column('tasks', 'strategyId',
               existing_type=sa.String(),
               type_=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
