"""strategyId default value

Revision ID: ad1a314ac577
Revises: 19a86cfedf6d
Create Date: 2024-03-11 21:52:53.752234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1a314ac577'
down_revision = '19a86cfedf6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
