"""caseName added in userpoints

Revision ID: e4b1dfd6c2a9
Revises: 43656cfc185d
Create Date: 2024-03-13 17:50:34.034997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b1dfd6c2a9'
down_revision = '43656cfc185d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userpoints', sa.Column('caseName', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userpoints', 'caseName')
    # ### end Alembic commands ###
