"""user's game config

Revision ID: e6ecec5e79c9
Revises: 29addea299e4
Create Date: 2025-02-24 10:40:29.711860

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e6ecec5e79c9"
down_revision = "29addea299e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usergameconfig",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("userId", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("gameId", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("experimentGroup", sa.String(), nullable=True),
        sa.Column("configData", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["gameId"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_usergameconfig_id"), "usergameconfig", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usergameconfig_id"), table_name="usergameconfig")
    op.drop_table("usergameconfig")
    # ### end Alembic commands ###
