"""ouath and logs table added

Revision ID: e9e9ff9e21fb
Revises: a034877f5226
Create Date: 2024-11-18 11:18:58.327230

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e9e9ff9e21fb"
down_revision = "a034877f5226"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("apirequests", sa.Column("oauth_user_id", sa.String(), nullable=True))
    op.add_column("games", sa.Column("oauth_user_id", sa.String(), nullable=True))
    op.add_column("gamesparams", sa.Column("oauth_user_id", sa.String(), nullable=True))
    op.add_column("kpimetrics", sa.Column("oauth_user_id", sa.String(), nullable=True))
    op.add_column("tasks", sa.Column("oauth_user_id", sa.String(), nullable=True))
    op.add_column("tasksparams", sa.Column("oauth_user_id", sa.String(), nullable=True))
    op.add_column("uptimelogs", sa.Column("oauth_user_id", sa.String(), nullable=True))
    op.add_column("useractions", sa.Column("oauth_user_id", sa.String(), nullable=True))
    op.add_column(
        "userinteractions", sa.Column("oauth_user_id", sa.String(), nullable=True)
    )
    op.add_column("userpoints", sa.Column("oauth_user_id", sa.String(), nullable=True))
    op.add_column("users", sa.Column("oauth_user_id", sa.String(), nullable=True))
    op.add_column("wallet", sa.Column("oauth_user_id", sa.String(), nullable=True))
    op.add_column(
        "wallettransactions", sa.Column("oauth_user_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wallettransactions", "oauth_user_id")
    op.drop_column("wallet", "oauth_user_id")
    op.drop_column("users", "oauth_user_id")
    op.drop_column("userpoints", "oauth_user_id")
    op.drop_column("userinteractions", "oauth_user_id")
    op.drop_column("useractions", "oauth_user_id")
    op.drop_column("uptimelogs", "oauth_user_id")
    op.drop_column("tasksparams", "oauth_user_id")
    op.drop_column("tasks", "oauth_user_id")
    op.drop_column("kpimetrics", "oauth_user_id")
    op.drop_column("gamesparams", "oauth_user_id")
    op.drop_column("games", "oauth_user_id")
    op.drop_column("apirequests", "oauth_user_id")
    # ### end Alembic commands ###
