"""new foreign key apiKey_used added in logs

Revision ID: eee9ef17ced6
Revises: cc88b5b558d7
Create Date: 2024-11-18 12:09:00.802700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee9ef17ced6'
down_revision = 'cc88b5b558d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikey', sa.Column('apiKey_used', sa.String(), nullable=True))
    op.create_foreign_key(None, 'apikey', 'apikey', ['apiKey_used'], ['apiKey'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apikey', type_='foreignkey')
    op.drop_column('apikey', 'apiKey_used')
    # ### end Alembic commands ###
