"""data into Wallettransaction

Revision ID: f08f7721328e
Revises: 1640253c71d5
Create Date: 2024-01-31 11:10:30.464643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f08f7721328e'
down_revision = '1640253c71d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallettransactions', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallettransactions', 'data')
    # ### end Alembic commands ###
