"""update externalTaskId

Revision ID: fc0435860dde
Revises: 394e21c63ac9
Create Date: 2024-01-19 11:13:29.572170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc0435860dde'
down_revision = '394e21c63ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_externalTaskId_key', 'tasks', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tasks_externalTaskId_key', 'tasks', ['externalTaskId'])
    # ### end Alembic commands ###
