apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: ${GAMIFICATIONENGINE_SERVICE_NAME}
  name: ${GAMIFICATIONENGINE_SERVICE_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ${GAMIFICATIONENGINE_SERVICE_NAME}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/game-backend: "true"
        io.kompose.service: ${GAMIFICATIONENGINE_SERVICE_NAME}
    spec:
      containers:
        - resources:
            limits:
              memory: 1Gi
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_URL
                  name: env-prod
            - name: DB_ENGINE
              valueFrom:
                configMapKeyRef:
                  key: DB_ENGINE
                  name: env-prod
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: env-prod
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: env-prod
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: env-prod
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: env-prod
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: env-prod
            - name: DEFAULT_CONVERTION_RATE_POINTS_TO_COIN
              valueFrom:
                configMapKeyRef:
                  key: DEFAULT_CONVERTION_RATE_POINTS_TO_COIN
                  name: env-prod
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  key: ENV
                  name: env-prod
            - name: VERSION_APP
              valueFrom:
                configMapKeyRef:
                  key: VERSION_APP
                  name: env-prod
          image: fvergaracl/game:v0.0.006
          name: game-api
      restartPolicy: Always
